# Public Domain (-) 2010-2011 The Togethr Authors.
# See the Togethr UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=live-server
GOFILES=\
	live-server.go\

include $(GOROOT)/src/Make.cmd
