# Public Domain (-) 2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=app-server
GOFILES=\
	handlers.go\
	main.go\

include $(GOROOT)/src/Make.cmd
