# Public Domain (-) 2011 The Togethr Authors.
# See the Togethr UNLICENSE file for details.

include $(GOROOT)/src/Make.inc

TARG=gaestore
GOFILES=\
		api.go\
		main.go\

include $(GOROOT)/src/Make.pkg
